version: '3.9'
services:
  service-registry:
    build: ./service-registry
    ports:
      - "8761:8761"
    networks:
      - microservices-net

  config-server:
    build: ./config-server
    ports:
      - "8088:8088"
    depends_on:
      - service-registry
    networks:
      - microservices-net

  department-service:
    build: ./department-service
    ports:
      - "8080:8080"
    depends_on:
      - config-server
    networks:
      - microservices-net

  employee-service:
    build: ./employee-service
    ports:
      - "8082:8082"
    depends_on:
      - config-server
    networks:
      - microservices-net

  api-gateway:
    build: ./api-gateway
    ports:
      - "8060:8060"
    depends_on:
      - department-service
      - employee-service
    networks:
      - microservices-net

networks:
  microservices-net:
