services:
  - type: web
    name: config-server
    env: docker
    dockerfilePath: ./config-server/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production

  - type: web
    name: service-registry
    env: docker
    dockerfilePath: ./service-registry/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: SPRING_CONFIG_IMPORT
        value: optional:configserver:http://config-server:8888

  - type: web
    name: department-service
    env: docker
    dockerfilePath: ./department-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-registry:8761/eureka/

  - type: web
    name: employee-service
    env: docker
    dockerfilePath: ./employee-service/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-registry:8761/eureka/

  - type: web
    name: api-gateway
    env: docker
    dockerfilePath: ./api-gateway/Dockerfile
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
        value: http://service-registry:8761/eureka/