server:
  port: 8088

spring:
  profiles:
    active: native
  application:
    name: config-server
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: config-server
