server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: api-gateway
    preferIpAddress: false
    instanceId: api-gateway:${random.value}
    statusPageUrlPath: /actuator/info
    healthCheckUrlPath: /actuator/health

management:
  endpoints:
    web:
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/v1/department/**
