server:
  port: 8060  # Render asignará su propio puerto, pero esto quedará como configuración interna

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-pb.onrender.com/eureka/  # URL de tu Service Registry en Render
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: api-gateway-pb.onrender.com  # Reemplaza con tu URL de API Gateway en Render
    nonSecurePort: 443
    securePortEnabled: true
    preferIpAddress: false
    statusPageUrl: https://${eureka.instance.hostname}/actuator/info
    healthCheckUrl: https://${eureka.instance.hostname}/actuator/health
    homePageUrl: https://${eureka.instance.hostname}/
    instanceId: ${eureka.instance.hostname}

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include: "*"  # Expone todos los endpoints de Actuator para monitoreo

spring:
  application:
    name: api-gateway  # Asegúrate de que esté definido para registrarse en Eureka
  cloud:
    gateway:
      routes:
        - id: employee-service
          uri: lb://employee-service
          predicates:
            - Path=/api/v1/employee/**
        - id: department-service
          uri: lb://department-service
          predicates:
            - Path=/api/v1/department/**