server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:8761/eureka/  # se comunica con el contenedor de Eureka
    fetchRegistry: true
    registerWithEureka: true
  instance:
    hostname: employee-service
    preferIpAddress: false
    instanceId: employee-service:${random.value}

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  application:
    name: employee-service
  cloud:
    discovery:
      enabled: true
