server:
  port: 8082

eureka:
  client:
    serviceUrl:
      defaultZone: https://service-registry-pb.onrender.com/eureka/  # URL de tu Service Registry en Render

management:
  tracing:
    sampling:
      probability: 1.0

spring:
  cloud:
    discovery:
      enabled: true